project_id = "sasmdprhssunrwxfkrtt"

[functions.analyze-measurement]
verify_jwt = false

[functions.analyze-spreadsheet]
verify_jwt = false

[functions.generate-mindmap]
verify_jwt = false

[functions.extract-survey]
verify_jwt = false

[functions.generate-budget]
verify_jwt = false

[functions.ocr-extract]
verify_jwt = false

[functions.ocr-mistral]
verify_jwt = false
